
all:
	cl main.cpp /I C:\Users\demon\SDL2\include /link C:\Users\demon\SDL2\lib\x64\SDL2.lib C:\Users\demon\SDL2\lib\x64\SDL2main.lib /SUBSYSTEM:CONSOLE /NODEFAULTLIB:libcmtd.lib opengl32.lib shell32.lib
