
all:
	cl main.cpp /I C:\Users\demon\SDL2\include /I c:\Users\demon\glew\include \
    /link C:\Users\demon\SDL2\lib\x64\SDL2.lib \
          C:\Users\demon\SDL2\lib\x64\SDL2main.lib \
          C:\Users\demon\glew\lib\Release\x64\glew32.lib \
    /SUBSYSTEM:CONSOLE /NODEFAULTLIB:libcmtd.lib opengl32.lib shell32.lib
    
