

all:
	cl main.cpp view.cpp matrix4x4.cpp /I C:\Users\demon\SDL2\include /I c:\Users\demon\glew\include \
    /link C:\Users\demon\SDL2\lib\x86\SDL2.lib \
          C:\Users\demon\SDL2\lib\x86\SDL2main.lib \
          C:\Users\demon\glew\lib\Release\Win32\glew32.lib \
    /SUBSYSTEM:CONSOLE /NODEFAULTLIB:libcmtd.lib opengl32.lib shell32.lib

